### ISSUE TITLE
"WebAssembly is not supported in this environment!"

### ISSUE THREAD

**Issue by GalacticLion7** [jesec/flood#143]
I am getting this error when trying to start Flood by executing `flood`, installed from the NPM package registry.

```Failed to start Flood:
Trace: Error: WebAssembly is not supported in this environment!
    at /Users/marwan/.config/yarn/global/node_modules/flood/dist/index.js:2:1261543
    at new Promise (native)
    at Object.d (/Users/marwan/.config/yarn/global/node_modules/flood/dist/index.js:2:1261411)
    at Object.84752 (/Users/marwan/.config/yarn/global/node_modules/flood/dist/index.js:2:1263440)
    at __webpack_require__ (/Users/marwan/.config/yarn/global/node_modules/flood/dist/index.js:2:1869905)
    at /Users/marwan/.config/yarn/global/node_modules/flood/dist/index.js:2:1870806
    at Object.<anonymous> (/Users/marwan/.config/yarn/global/node_modules/flood/dist/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.<anonymous> (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at /Users/marwan/.config/yarn/global/node_modules/flood/dist/index.js:2:1263585
```

**Comment by jesec** [comment]
Check your Node.js version.

**Comment by GalacticLion7** [comment]
Figured out the issue: it was because I was using GraalJS.
