### ISSUE TITLE
Can't create torrent from my files, NotFoundError: Not Found 

### ISSUE THREAD

**Issue by CyberPoison** [jesec/flood#248]
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used: Docker / tag master from https://hub.docker.com/r/jesec/flood
 
- Operating system and version: Ubuntu 18.04
- Torrent client and version: rtorrent 0.9.8

## Summary

Can't Create Torrent files to send to a private tracker

## Expected Behavior

Retrieve the Torrent file created

## Current Behavior

Still spinning for a while an then nothing happens no created on tags and etc...
Logs on my K8S is 
```
NotFoundError: Not Found
    at SendStream.error (/usr/local/lib/node_modules/@jesec/flood/dist/index.js:2:872866)
    at SendStream.pipe (/usr/local/lib/node_modules/@jesec/flood/dist/index.js:2:876530)
    at sendfile (/usr/local/lib/node_modules/@jesec/flood/dist/index.js:2:187691)
    at ServerResponse.sendFile (/usr/local/lib/node_modules/@jesec/flood/dist/index.js:2:183212)
    at ServerResponse.download (/usr/local/lib/node_modules/@jesec/flood/dist/index.js:2:184098)
    at c.default.promises.writeFile.then.code (/usr/local/lib/node_modules/@jesec/flood/dist/index.js:2:1266090)
 ```
Path are correctly monted as /mnt:/mnt and /opt/appdata/flood-ui:/data
## Possible Solution
Not fund

## Steps to Reproduce

1. Create a new container with the master tag set 
2. Link your flood with your rtorrent sock file
3. Create a fresh account 
4. Create a torrent

**Comment by jesec** [comment]
Try `master-dbg` image. It is a drop-in replacement which provides better stacktraces.

**Comment by jesec** [comment]
@CyberPoison any update?

**Comment by jesec** [comment]
ef4e41f6f0d5f7ea08c70efcf7c6e4a71d117db4 resolved this issue. Please let me know if it is still relevant.
