### ISSUE TITLE
Unable to run Flood as a systemd service

### ISSUE THREAD

**Issue by CodyRWhite** [jesec/flood#358]
Type: Bug Report

- [ x ] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - Version 4.6.1
- Environment name and version:
  - Node.js version `node --version` v16.4.1
  - npm version `npm --version` 7.19.1
  - Web browser `name and version` N/A
- Operating system and version: RockyLinux 8.4
- Torrent client and version: rTorrent - Latest

## Summary

I am able to run flood manually using flood -h 0.0.0.0 however when I attempt to run this with systemd the service fails and returns an error 

```
cat > /etc/systemd/system/flood.service << DATA_BLOCK
[Unit]
Description=Flood
After=network.target

[Service]
Type=simple
KillMode=process
Restart=on-failure
User=rtorrent
Group=rtorrent
ExecStart=/usr/local/bin/flood -h 0.0.0.0
WorkingDirectory=/home/rtorrent

[Install]
WantedBy=multi-user.target
DATA_BLOCK
```
## Current Behavior
```
systemd[1]: Started Flood.
-- Subject: Unit flood.service has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit flood.service has finished starting up.
-- 
-- The start-up result is done.
flood[12072]: /usr/local/lib/node_modules/flood/dist/index.js:452
flood[12072]: ***************************************************************************** */var extendStatics=function(t,s){extendStatics=Object.setPrototypeOf||{__proto__:[]}ins>
flood[12072]: Error: yargs supports a minimum Node.js version of 12. Read our version support policy: https://github.com/yargs/yargs#supported-nodejs-versions
flood[12072]:     at Object.9567 (/usr/local/lib/node_modules/flood/dist/index.js:452:285467)
flood[12072]:     at __nccwpck_require__ (/usr/local/lib/node_modules/flood/dist/index.js:452:560293)
flood[12072]:     at Object.5387 (/usr/local/lib/node_modules/flood/dist/index.js:452:286028)
flood[12072]:     at __nccwpck_require__ (/usr/local/lib/node_modules/flood/dist/index.js:452:560293)
flood[12072]:     at Object.167 (/usr/local/lib/node_modules/flood/dist/index.js:452:52861)
flood[12072]:     at __nccwpck_require__ (/usr/local/lib/node_modules/flood/dist/index.js:452:560293)
flood[12072]:     at Module.1743 (/usr/local/lib/node_modules/flood/dist/index.js:452:60195)
flood[12072]:     at __nccwpck_require__ (/usr/local/lib/node_modules/flood/dist/index.js:452:560293)
flood[12072]:     at /usr/local/lib/node_modules/flood/dist/index.js:452:561245
flood[12072]:     at Object.<anonymous> (/usr/local/lib/node_modules/flood/dist/index.js:452:561329)
systemd[1]: flood.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: flood.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The unit flood.service has entered the 'failed' state with result 'exit-code'.
```

## Steps to Reproduce

```
### install Flood
dnf install nodejs -y

su rtorrent 
cd /home/rtorrent
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm install node
npm install -g npm
npm install -g flood

exit 

cat > /etc/systemd/system/flood.service << DATA_BLOCK 
[Unit]
Description=Flood
After=network.target

[Service]
Type=simple
KillMode=process
Restart=on-failure
User=rtorrent
Group=rtorrent
ExecStart=/usr/local/bin/flood -h 0.0.0.0
WorkingDirectory=/home/rtorrent

[Install]
WantedBy=multi-user.target
DATA_BLOCK

firewall-cmd --zone=public --permanent --add-port=3000/tcp
firewall-cmd --reload

systemctl enable flood
systemctl start flood

journalctl -xe
```

**Comment by CodyRWhite** [comment]
Really sorry if this has been discussed elsewhere. I checked the documentation and prior issues I was not able to locate anything for this newer repo.

**Comment by jesec** [comment]
`a minimum Node.js version of 12`

you need to make sure that the version of systemwide Node.js (the one systemd services use, not your per-user Node) is at least 12.

**Comment by jesec** [comment]
Unfortunately `nvm` does not install Node.js globally, and as such it has no effect (on systemd service). 

You may have to use the standalone executable that bundles Node.js runtime, or figure out a way to let the Flood service to use an appropriate Node version.

**Comment by CodyRWhite** [comment]
Thanks I was able to get this fixed. 

If anyone comes across this. 

RHEL 8 (RHEL, CentOS, Rocky) 

```
dnf module install nodejs:14 -y
dnf install nodejs -y

npm install --global flood

firewall-cmd --zone=public --permanent --add-port=3000/tcp
firewall-cmd --reload

cat > /etc/systemd/system/flood.service << DATA_BLOCK
[Unit]
Description=Flood
Documentation=https://github.com/jesec/flood/wiki
After=network.target

[Service]
Type=simple
KillMode=process
Restart=on-failure
User=rtorrent
Group=rtorrent
ExecStart=/usr/local/bin/flood -h 0.0.0.0
WorkingDirectory=/home/rtorrent

[Install]
WantedBy=multi-user.target
DATA_BLOCK

systemctl enable flood
systemctl start flood
```
