### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by artik** [jesec/flood#44]
Hi, I'm having a new error when launching Flood in a docker container. I tried the latest commit: `bdb8144f4b1d4921d9d60f28424aab5c31f455f6`. Here is the error:

```
SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flood@3.1.0 start: `node --use_strict dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flood@3.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Here is my Dockerfile:

```
FROM alpine:3.11

ARG RTORRENT_VER=0.9.8
ARG LIBTORRENT_VER=0.13.8
ARG MEDIAINFO_VER=19.09
ARG BUILD_CORES

ENV UID=1024 GID=100 \
    FLOOD_SECRET=supersecret \
    WEBROOT=/ \
    RTORRENT_SCGI=0 \
    PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

RUN NB_CORES=${BUILD_CORES-`getconf _NPROCESSORS_CONF`} \
 && apk -U upgrade \
 && apk add -t build-dependencies \
    build-base \
    git \
    libtool \
    automake \
    autoconf \
    wget \
    tar \
    xz \
    zlib-dev \
    cppunit-dev \
    openssl-dev \
    ncurses-dev \
    curl-dev \
    binutils \
    linux-headers \
 && apk add \
    ca-certificates \
    curl \
    ncurses \
    openssl \
    gzip \
    zip \
    zlib \
    s6 \
    su-exec \
    python \
    nodejs \
    nodejs-npm \
    unrar \
    findutils \
 && cd /tmp && mkdir libtorrent rtorrent \
 && cd libtorrent && wget -qO- https://github.com/rakshasa/libtorrent/archive/v${LIBTORRENT_VER}.tar.gz | tar xz --strip 1 \
 && cd ../rtorrent && wget -qO- https://github.com/rakshasa/rtorrent/releases/download/v${RTORRENT_VER}/rtorrent-${RTORRENT_VER}.tar.gz | tar xz --strip 1 \
 && cd /tmp \
 && git clone https://github.com/mirror/xmlrpc-c.git \
 && cd /tmp/xmlrpc-c/advanced && ./configure && make -j ${NB_CORES} && make install \
 && cd /tmp/libtorrent && ./autogen.sh && ./configure && make -j ${NB_CORES} && make install \
 && cd /tmp/rtorrent && ./autogen.sh && ./configure --with-xmlrpc-c && make -j ${NB_CORES} && make install \
 && cd /tmp \
 && wget -q http://mediaarea.net/download/binary/mediainfo/${MEDIAINFO_VER}/MediaInfo_CLI_${MEDIAINFO_VER}_GNU_FromSource.tar.gz \
 && wget -q http://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VER}/MediaInfo_DLL_${MEDIAINFO_VER}_GNU_FromSource.tar.gz \
 && tar xzf MediaInfo_DLL_${MEDIAINFO_VER}_GNU_FromSource.tar.gz \
 && tar xzf MediaInfo_CLI_${MEDIAINFO_VER}_GNU_FromSource.tar.gz \
 && cd /tmp/MediaInfo_DLL_GNU_FromSource && ./SO_Compile.sh \
 && cd /tmp/MediaInfo_DLL_GNU_FromSource/ZenLib/Project/GNU/Library && make install \
 && cd /tmp/MediaInfo_DLL_GNU_FromSource/MediaInfoLib/Project/GNU/Library && make install \
 && cd /tmp/MediaInfo_CLI_GNU_FromSource && ./CLI_Compile.sh \
 && cd /tmp/MediaInfo_CLI_GNU_FromSource/MediaInfo/Project/GNU/CLI && make install \
 && strip -s /usr/local/bin/rtorrent \
 && strip -s /usr/local/bin/mediainfo \
 && ln -sf /usr/local/bin/mediainfo /usr/bin/mediainfo \

 && cd /usr  \
 && git clone https://github.com/jesec/flood  \
 && cd /usr/flood  \
 && npm install && npm cache clean --force \
 && apk del build-dependencies \
 && rm -rf /var/cache/apk/* /tmp/*

COPY rootfs /

RUN chmod +x /usr/local/bin/* /etc/s6.d/*/* /etc/s6.d/.s6-svscan/* \
 && cd /usr/flood/ && npm run build

VOLUME /data /flood-db

EXPOSE 3000 49184 49184/udp

LABEL description="BitTorrent client with WebUI front-end" \
      rtorrent="rTorrent BiTorrent client v$RTORRENT_VER" \
      libtorrent="libtorrent v$LIBTORRENT_VER" \
      maintainer="flosoft <florian@florianjensen.com>"

CMD ["run.sh"]
```

Any help?

**Comment by jesec** [comment]
I noticed that you are using `apk` to add `nodejs` package. Unfortunately `nodejs` came with the distribution may be too old to run Flood. You should try to switch to the latest official NodeJS docker image. (e.g. `node:alpine`) Plus, I don't really recommend building Flood from source in cases where sources are not modified. You should use `npm` to [install](https://github.com/jesec/flood#installation) Flood or base upon the [Flood docker image](https://hub.docker.com/repository/docker/jesec/flood).  Rolling builds are also available.

**Comment by Roguyt** [comment]
I also got a similar issue when building flood by myself on Node 12.
The issue is that optional chaining isn't officially supported until Node 14.
Updating to Node 14 fixes the issue.

The long term solution is either to target a lower es version for the TS transpilation or bump the required version to >= 14

**Comment by jesec** [comment]
Flood always targets the `Current` Node version, as documented in [README](https://github.com/jesec/flood#pre-requisites).

I do wish to support at least one or two recent LTS version, though. That's why [CI scripts](https://github.com/jesec/flood/runs/1205831550) try to build on Node 12. It is interesting that such issue is not spotted at build-time. I will see what I can do to restore Node 12 support.

**Comment by Roguyt** [comment]
My bad regarding the `Current` Node version, I skimmed through the changelog and saw that Node >= 12 was the minimum on the fork.

The CI won't pick it up because it is a runtime error based on the fact that Node version below 14 do not support optional chaining out of the box. I believe some later minor version of 12 & 13 can access it through harmony flag but it isn't a guaranteed fact.

I'll try to tweak a bit your TS options to see if it's possible to target Node 12 easily without any codebase change.
