### ISSUE TITLE
ModuleBuildError: 'Const declarations' require an initialization value

### ISSUE THREAD

**Issue by dstaley** [jesec/flood#505]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - `v4.7.0`
- Environment name and version:
  - Node.js version: `v16.13.2`
  - npm version: `8.1.2`
  - Web browser: N/A
- Operating system and version: `docker.io/node:alpine-16`
- Torrent client and version: N/A

## Summary

When running `npm run build` in the `v4.7.0` release, I get a `ModuleBuildError`

## Expected Behavior

The build is successful.

## Current Behavior

```
Creating an optimized production build...
ℹ Compiling Webpack
✔ Webpack: Compiled with some errors in 636.00ms
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /usr/src/app/client/src/javascript/app.tsx: 'Const declarations' require an initialization value. (23:14)

  21 | const Register = lazy(() => import(/* webpackPrefetch: true */ './routes/Register'));
  22 |
> 23 | const FloodApp: FC = observer(() => {
     |               ^
  24 |   useEffect(() => {
  25 |     UIStore.registerDependency([
  26 |       {
    at Parser._raise (/usr/src/app/node_modules/@babel/parser/lib/index.js:541:17)
    at Parser.raiseWithData (/usr/src/app/node_modules/@babel/parser/lib/index.js:534:17)
    at Parser.raise (/usr/src/app/node_modules/@babel/parser/lib/index.js:495:17)
    at Parser.parseVar (/usr/src/app/node_modules/@babel/parser/lib/index.js:13813:18)
    at Parser.parseVarStatement (/usr/src/app/node_modules/@babel/parser/lib/index.js:13623:10)
    at Parser.parseStatementContent (/usr/src/app/node_modules/@babel/parser/lib/index.js:13208:21)
    at Parser.parseStatement (/usr/src/app/node_modules/@babel/parser/lib/index.js:13139:17)
    at Parser.parseBlockOrModuleBlockBody (/usr/src/app/node_modules/@babel/parser/lib/index.js:13728:25)
    at Parser.parseBlockBody (/usr/src/app/node_modules/@babel/parser/lib/index.js:13719:10)
    at Parser.parseProgram (/usr/src/app/node_modules/@babel/parser/lib/index.js:13061:10)
    at processResult (/usr/src/app/node_modules/webpack/lib/NormalModule.js:743:19)
    at /usr/src/app/node_modules/webpack/lib/NormalModule.js:844:5
    at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /usr/src/app/node_modules/babel-loader/lib/index.js:59:103
```

## Possible Solution

¯\\\_(ツ)\_/¯

## Steps to Reproduce

```dockerfile
FROM docker.io/node:16-alpine AS nodebuild

WORKDIR /usr/src/app/

RUN apk update \
    && apk add --no-cache unzip \
    && wget https://github.com/jesec/flood/archive/refs/tags/v4.7.0.zip \
    && unzip v4.7.0.zip \
    && rm v4.7.0.zip \
    && mv flood-4.7.0/* . \
    && rm -rf flood-4.7.0 \
    && npm ci \
    && npm run build
```

**Comment by jesec** [comment]
You would have to check your environment and setup. 

CI was successful with v4.7.0, and I do not expect issues with a proper Node.js installation. 

https://github.com/jesec/flood/runs/3848236385?check_suite_focus=true

**Comment by jesec** [comment]
Your Dockerfile is wrong. 

* does not include . (dot) files.
